# Generated by Django 4.0.10 on 2023-11-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0006_articulo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='categoria',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='genero',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
