# Generated by Django 4.2.7 on 2023-12-04 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articulos", "0007_alter_articulo_categoria_alter_articulo_genero"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulo",
            name="autor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
