# Generated by Django 4.2.7 on 2023-12-09 16:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("articulos", "0008_articulo_autor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comentario",
            old_name="articulo",
            new_name="Articulo",
        ),
        migrations.AlterField(
            model_name="articulo",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
